version: '3.9'

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mycats
    # volumes:
    #   - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin

  scaapi:
    container_name: sca_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - pgadmin
    volumes:
      - "./config_example.yaml:/config.yaml"
    command: "-config /config.yaml"
